- src/Components/Employees/Modals/modal.module.css
- src/Components/Shared/Loader/Loader.jsx
- src/Components/Shared/Loader/loader.module.css
> TG-39-Shared component: Loader

- src/Components/Shared/Loader/Loader.jsx
- src/Components/Shared/Loader/loader.module.css
> TG-49-loader-hotfix

- src/Components/Footer/footer.module.css
- src/Components/Footer/index.js
- src/Components/Layout/index.js
My job was to change the footer styles to match the figma. it was not necessary to make the shared components with footer.
>  BaSP-TG-33: Footer

- src/Components/Shared/Buttons/Buttons.jsx
- src/Components/Shared/Buttons/buttons.module.css
In this component will be create buttons submit, close, add and edit
> BaSP-TG-32: Button

- src/Components/Header/header.module.css
- src/Components/Header/index.js
- src/Components/Layout/index.js
- src/Components/NavBar/NavBar.jsx
- src/Components/NavBar/navBar.module.css
I moved the navBar from the header component to a new component called "NavBar", I also changed the Layout to include the new component
> BaSP-TG-37: NavBar 

- src/Components/Shared/Modal/Modal.jsx
- src/Components/Shared/Modal/modal.module.css
- src/Components/Tasks/index.js
- src/Components/Tasks/tasks.module.css
> BaSP-TG-35: Modal

- src/Components/Shared/Row/Row.jsx
- src/Components/Shared/Row/row.module.css
- Created a sheared component: Rows
- Created css to component.
> BaSP-TG-34: Rows component

- src/Components/Shared/Field/Input.jsx
- src/Components/Shared/Field/RadioButton.jsx
- src/Components/Shared/Field/input.module.css
> BaSP-TG-38: Field Shared Components

- src/Components/Shared/Row/Row.jsx
- src/Components/Shared/Table/Table.jsx
- src/Components/Shared/Table/table.module.css
In this branch:
¿How to implement the Table component? 
1. import the Table component on your  List.jsx file 
2. Once inside your List file, delete the tag <table> and everything inside it.  Instead, call the Table component and give it the props it needs, as you can see here:  
`import React from 'react';
import Table from '../../Shared/Table/Table';
const List = ({ list, deleteItem, editItem }) => {
return (
<Table
title={'Projects'}
data={list}
headersColumns={['ID', 'Project Name', 'Client', 'Start Date', 'Finish Date', 'Status']}
headers={['_id', 'project_name', 'client', 'start_date', 'finish_date', 'active']}
deleteItem={deleteItem}
editItem={editItem}
/>
);
};
export default List;`
- Inside 'title' it should go the name of the entity, inside 'headersColums' it should go an array …
> BaSP-TG-47: Table shared components

- src/Components/Footer/index.js
- src/Components/NavBar/NavBar.jsx
> BaSP-TG-46: Implement shared component -Layout

- src/Components/Projects/FormAdd/AddProject.jsx
- src/Components/Projects/List/List.jsx
- src/Components/Projects/index.js
-Implement Rows
-Implement Field
-Implement Button
> BaSP-TG-42: Projects - The implementation of the shared components.

- src/Components/Employee/Home/home.module.css
- src/Components/Employee/Home/index.js
- src/Components/Employee/index.js
- src/Components/Home/index.js
- src/Components/Layout/index.js
- src/Components/Shared/NavBar/navBar.module.css
- src/Components/SuperAdmin/Home/home.module.css
- src/Components/SuperAdmin/Home/index.js
- src/Components/SuperAdmin/index.js
- src/Components/SuperAdmin/superAdmin.module.css
> BaSP-Feature-TG-80: Employee, home

- src/Components/Shared/Buttons/buttons.module.css
- src/Components/Shared/Field/Input.jsx
- src/Components/Shared/Field/input.module.css
- src/Components/SuperAdmin/Projects/Form/ProjectForm.jsx
- src/Components/SuperAdmin/Projects/Form/projectForm.module.css
- src/Components/SuperAdmin/Projects/List/List.jsx
- src/Components/SuperAdmin/Projects/index.js
- src/redux/projects/thunks.js
**Update add and edit form using "React-Hook-Form" library**
> BaSP-TG-79: Project Update Form

- src/Components/SuperAdmin/TimeSheets/Form/FormTimeSheet.jsx
- src/Components/SuperAdmin/TimeSheets/List/List.jsx
- src/Components/SuperAdmin/TimeSheets/index.js
> BaSP-TG-78: TimeSheet Update Form

- src/Components/Shared/Buttons/buttons.module.css
- src/Components/Shared/Field/input.module.css
- src/Components/SuperAdmin/SuperAdmins/Form/SuperAdminForm.jsx
- src/Components/SuperAdmin/SuperAdmins/Form/superAdminForm.module.css
- src/Components/SuperAdmin/SuperAdmins/ListSuperAdmins/ListSuperAdmins.jsx
- src/redux/superAdmins/thunks.js
> BaSP-TG-75: SuperAdmins Update Form 

- src/Components/SuperAdmin/Tasks/Form/Form.jsx
- src/Components/SuperAdmin/Tasks/Form/form.module.css
- src/Components/SuperAdmin/Tasks/List/index.jsx
- src/Components/SuperAdmin/Tasks/index.js
- src/redux/tasks/actions.js
- src/redux/tasks/reducer.js
- src/redux/tasks/thunks.js
**Update add and edit form using "React-Hook-Form" library**
> BaSP-TG-76: Task Update Form

- src/Components/Employee/Sign-up/index.jsx
- src/Components/Employee/Sign-up/sign-up.module.css
- src/Components/Employee/index.js
- src/Components/Shared/index.js
- src/redux/employees/thunks.js
> BaSP-Feature-TG-84: Employee Sign-Up Form

- package-lock.json
- package.json
- src/helper/firebase/index.js
> BaSP-TG-86: Firebase initial setup

- src/helper/firebase/index.js
- src/redux/auth/actions.js
- src/redux/auth/constants.js
- src/redux/auth/reducer.js
- src/redux/auth/thunks.js
- src/redux/store.js
> BaSP-TG-94-Redux

- src/Components/Shared/Field/Input.jsx
- src/Components/Shared/Row/Row.jsx
- src/Components/Shared/Row/row.module.css
- src/Components/Shared/Table/Table.jsx
In this branch, a few changes were made to the shared components to improve the performance:
> Hotfix: Update Row and Table shared components

- src/Components/Shared/Table/Table.jsx
> TG-119: fix Table

- src/Components/Auth/Login/index.jsx
> BaSP-Hotfix-TG-126: Login error message

- src/Components/SuperAdmin/Admins/Form/AdminForm.jsx
- src/Components/SuperAdmin/Admins/Form/adminForm.module.css
Superadmin:
email: roberto@gmail.com
password: asdasd123
> BaSP-Feature-TG-128: Admins validations and css fix

- src/Components/Auth/Login/index.jsx
- src/Components/Auth/Login/login.module.css
- src/Components/Auth/SignUp/index.jsx
- src/Components/Auth/SignUp/sign-up.module.css
- src/Components/Employee/Projects/index.jsx
- src/Components/Employee/TimeSheet/Form/Form.jsx
- src/Components/Employee/TimeSheet/index.jsx
- src/Components/Shared/Modal/modal.module.css
- src/Routes/home.jsx
- src/redux/employees/thunks.js
- src/redux/tasks/reducer.js
> BaSP-TG-133: add timsheet validations, fix sign-up and add styles in forms

- src/Components/Admin/Employees/employees.module.css
- src/Components/Employee/TimeSheet/index.jsx
- src/Components/Shared/Loader/loader.module.css
- src/redux/employees/thunks.js
> hotfix-TG-107: 

- src/Components/Admin/Projects/Form/ProjectForm.jsx
- src/Components/Admin/Projects/Form/projectForm.module.css
- src/Components/Auth/SignUp/index.jsx
- src/Components/Employee/Profile/index.jsx
- src/Components/Employee/Projects/Form/EmployeeForm.jsx
- src/Components/Employee/Projects/Form/projectForm.module.css
- src/Components/Employee/Projects/Tasks/Form/Form.jsx
- src/Components/Employee/Projects/Tasks/Form/form.module.css
- src/Components/Employee/Projects/Tasks/tasks.module.css
- src/Components/Employee/Projects/index.jsx
- src/Components/Employee/TimeSheet/Form/Form.jsx
- src/Components/Employee/TimeSheet/Form/form.module.css
- src/Components/Shared/Buttons/buttons.module.css
- src/Components/SuperAdmin/Admins/Form/AdminForm.jsx
- src/Components/SuperAdmin/Admins/Form/adminForm.module.css
- src/Components/SuperAdmin/Admins/index.js
> BaSP-TG-131: Fix Buttons and change button "close" => "x"

- src/Components/Employee/Projects/Tasks/Form/form.module.css
- src/Components/Employee/TimeSheet/Form/Form.jsx
- src/Components/Shared/Modal/modal.module.css
- src/Components/Shared/Table/table.module.css
- src/Components/SuperAdmin/Admins/admins.module.css
Hice una banda de cosas re poco importantes
> Hotfix styles & timesheet

- src/Components/Employee/Home/index.js
> BaSP-TG-136: hotfix home page on employee
